**<font color='blue'><font size='4'>Question 1.	Load gateway_questions.csv from gateway_questions.zip. This contains data for orders sent to various gateways (connections to the exchange), and whether or not the orders succeeded (hit the exchange before competitors). Does the data suggest that any particular gateway or gateways are faster than others? (Please share your analysis code/notebook with us).**

In [1]:
import pandas as pd
import datetime as dt

In [2]:
RawData = pd.read_csv('gateway_question.csv')
RawData

           timestamp  gateway_targeted  succeeded  price  side  quantity
0       1.813080e+05                 6      False  20000  sell        89
1       3.584480e+05                 3      False  19999  sell        38
2       4.760810e+05                 2      False  19999   buy        17
3       1.007773e+06                 2      False  19999   buy        88
4       1.554167e+06                 7      False  19999   buy        42
5       2.447619e+06                 6      False  19995   buy        99
6       3.310771e+06                 1      False  19995  sell        97
7       3.974259e+06                 2      False  19993   buy        47
8       4.504553e+06                 5      False  19993   buy        29
9       5.253624e+06                 6      False  19993  sell        76
10      5.416702e+06                 1      False  19991   buy        25
11      5.759209e+06                 6      False  19991  sell        83
12      6.425540e+06                 5      False  19991  sell        82
13      7.288570e+06                 6      False  19994  sell        23
14      8.255385e+06                 8      False  19993   buy         5
15      9.092331e+06                 6      False  19991  sell        85
16      9.809157e+06                 8      False  19992   buy        21
17      1.039719e+07                 8      False  19992   buy         9
18      1.106999e+07                 5      False  19994   buy        64
19      1.111302e+07                 3      False  19991   buy         4
20      1.175762e+07                 8      False  19994  sell        52
21      1.199315e+07                 5      False  19993  sell        58
22      1.273856e+07                 5      False  19993  sell        30
23      1.282847e+07                 3      False  19990   buy        58
24      1.377043e+07                 5      False  19991  sell        52
25      1.466303e+07                 1      False  19993   buy        92
26      1.507064e+07                 6      False  19992   buy        75
27      1.509254e+07                 6      False  19994   buy        19
28      1.530399e+07                 3      False  19994   buy        27
29      1.586688e+07                 1      False  19995   buy        98
...              ...               ...        ...    ...   ...       ...
499970  2.499960e+11                 1      False  18665  sell        44
499971  2.499960e+11                 8      False  18667   buy        41
499972  2.499970e+11                 1      False  18670  sell        54
499973  2.499980e+11                 7      False  18668   buy        74
499974  2.499990e+11                 2      False  18666  sell        77
499975  2.499990e+11                 7      False  18663   buy        31
499976  2.499990e+11                 3      False  18665  sell        77
499977  2.499990e+11                 3      False  18666   buy        46
499978  2.500000e+11                 5      False  18665   buy        21
499979  2.500000e+11                 2      False  18668  sell        54
499980  2.500010e+11                 3      False  18666   buy        49
499981  2.500020e+11                 4      False  18666   buy        94
499982  2.500020e+11                 1      False  18668  sell        69
499983  2.500020e+11                 5      False  18663   buy        92
499984  2.500020e+11                 1      False  18665   buy        29
499985  2.500020e+11                 8      False  18663  sell        54
499986  2.500030e+11                 4      False  18666  sell        78
499987  2.500040e+11                 1      False  18665  sell        18
499988  2.500040e+11                 5      False  18670   buy         8
499989  2.500040e+11                 6      False  18667  sell        22
499990  2.500050e+11                 7      False  18666  sell        97
499991  2.500050e+11                 6      False  18668  sell        38
499992  2.500050e+11                 3      False  18670   buy        57
499993  2.500050e+11                 2      False  18669  sell        54
499994  2.500060e+11                 5      False  18671  sell        56
499995  2.500070e+11                 7      False  18668   buy        58
499996  2.500080e+11                 7      False  18666  sell        49
499997  2.500090e+11                 6      False  18666   buy        92
499998  2.500100e+11                 8      False  18665  sell        87
499999  2.500100e+11                 1      False  18665  sell        80

[500000 rows x 6 columns]

**There are 2 approaches to find out which gateway with fast speed:**
* Approach 1 based on all cases (both successful orders and fail orders)
* Approach 2 based on cases with successful orders

# Approach 1: Both successful orders and failed orders

In [3]:
Data_1= RawData[['gateway_targeted','timestamp']].groupby(['gateway_targeted']).agg(['count','mean'])
Data_1

                 timestamp
                     count          mean
gateway_targeted
1                    62212  1.245095e+11
2                    62641  1.247914e+11
3                    62449  1.246421e+11
4                    62715  1.253725e+11
5                    62394  1.255893e+11
6                    62796  1.249627e+11
7                    62277  1.251341e+11
8                    62516  1.252091e+11

In [4]:
Data_1[Data_1['timestamp']['mean']==Data_1['timestamp']['mean'].min()]

                 timestamp
                     count          mean
gateway_targeted
1                    62212  1.245095e+11

__<font color='green'>Conclusion: In full base, gateway 1 is faster than others__

# Approach 2: Only successful orders base

In [5]:
RawData_temp= RawData.loc[(RawData["succeeded"]==True)]
Data_2= RawData_temp[['gateway_targeted','timestamp']].groupby(['gateway_targeted']).agg(['count','mean'])
Data_2

                 timestamp
                     count          mean
gateway_targeted
1                     2130  1.267929e+11
2                      125  1.330267e+11
3                      455  1.209107e+11
4                       75  1.200344e+11
5                      710  1.214022e+11
6                     1167  1.254533e+11
7                       29  1.311695e+11
8                      235  1.253035e+11

In [6]:
Data_2[Data_2['timestamp']['mean']==Data_2['timestamp']['mean'].min()]

                 timestamp
                     count          mean
gateway_targeted
4                       75  1.200344e+11

__<font color='green'> Conclusion: In base including successful cases only, gateway 4 is faster than others (speed per 1 order basis)__